---
- hosts: all
  become: yes
  gather_facts: yes
  tasks: 
   - name: i want to install apache2 on node server
     apt:  
      name: apache2
      state: present 

   - name: i want to start webserver (service apache2 start)
     service: 
      name: apache2
      state: started